SOURCES:=\
caching/subset-caching.cpp \
caching/eqcache.cpp \
caching/empty-cache.cpp \
caching/compose-eq-cache.cpp \
caching/compose-ncache.cpp \
caching/caching.cpp \
caching/caching-tests.cpp \
caching/constraint-cache.cpp


LIB=analysis

include ../../new-rules/build-targets.mk
