# On win32, all these extra libraries are required.
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libws2_32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libiphlpapi.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libpsapi.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/liblmgr_md.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libwsock32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libmsvcrt.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libnetapi32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libcrvs.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libnoact.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libsb.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libcomdlg32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libcomctl32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libchkstk.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libmingw32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libmoldname.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libmingwex.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libuser32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libkernel32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libadvapi32.a
COMPILER_FILES+=$(COMPILER_LIB_DIR)/libshell32.a

