SOURCES:=\
sm/state/compose-nstate.cpp \
sm/state/constraint-store.cpp \
sm/state/empty-state.cpp \
sm/state/fpp-syn-store.cpp \
sm/state/sink-deriver-state.cpp \
sm/state/state.cpp \
sm/state/store.cpp \
sm/state/unique.cpp \


LIB=analysis

include ../../../new-rules/build-targets.mk

